version: '3'
services: 
    web:
        image: quizz-app
        build: .
        command: "node app.js"
        ports: 
            - "3000:3000"
        depends_on: 
            - "mongo"
    mongo:
        image: "mongo"
        ports: 
            - "2717:27017"