version: "3"
services:
  web:
    image: quizz-app
    build: .
    command: "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
    volumes:
      - ./:/usr/src/app
  mongo:
    image: "mongo"
    ports:
      - "2717:27017"
